version: '3'

# 创建外部网络，name: local-server-network
# docker network create local-server-network
# 登录时使用 cn=admin,dc=mydomain,dc=com
# 创建Generic: Organisational Unit
# 创建Generic: Posix Group
# 创建Generic: User Account

services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "cloud"
      LDAP_DOMAIN: "mydomain.com"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - "./data/database:/var/lib/ldap"
      - "./data/config:/etc/ldap/slapd.d"
    #networks:
    #  - webnet

  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap-server:ldap"
    #networks:
    #  - webnet

networks:
  default:
    external: true
    name: local-server-network
