version: '3'

services:
  ldap-server:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "cloud"
      LDAP_DOMAIN: "hugang.io"
      LDAP_ADMIN_PASSWORD: "admin"
    volumes:
      - "./data/database:/var/lib/ldap"
      - "./data/config:/etc/ldap/slapd.d"

  ldap-admin:
    image: osixia/phpldapadmin:latest
    restart: always
    container_name: ldap-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    links:
      - "ldap-server:ldap"
    networks:
      - hugang


networks:
  hugang:
    external: true


