version: '3.1'

services:
  redmine-server:
    image: redmine
    container_name: redmine-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_DB_ENCODING: utf8mb4
    volumes:
      - ./data:/data
    networks:
      - hugang
  redmine-db:
    image: mysql:5.7
    restart: always
    container_name: redmine-db
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      - ./data/db:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - hugang

networks:
  hugang:
    external: true

