version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    container_name: kanboard
    ports:
      - "8081:80"
      #- "443:443"
    volumes:
      - "./data/kanboard_data:/var/www/app/data"
      - "./config.php:/var/www/app/config.php"
      - "./data/kanboard_plugins:/var/www/app/plugins"
    networks:
      - hugang
networks:
  hugang:
    external: true
