version: '2'
services:
  app:
    image: nextcloud
    restart: always
    container_name: nextcloud-server
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
networks:
  hugang:
    external: true
