version: '3'

services:
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - ./samba/pub:/mnt/pub:rw
    command: >
      -s "public;/mnt/pub;yes;no;yes;all;none"
      -p
    restart: unless-stopped
    networks:
      - hugang

networks:
  hugang:
    external: true
