version: '3.7'
services:
  nginx-server:
    image: nginx
    container_name: nginx-server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
      - ./conf/ssl:/etc/nginx/ssl:ro
      - ./conf/conf.d:/etc/nginx/conf.d
    networks:
      - hugang

networks:
  hugang:
    external: true

