version: "3"

services:
  gitea-server:
    image: gitea/gitea
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
       - "8083:3000"
       - "10022:22"
    depends_on:
      - gitea-db

  gitea-db:
    image: mysql:5.7
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  default:
    external: true
    name: local-server-network
