version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins-lts-docker
    #privileged: true
    container_name: jenkins-server
    environment:
      - DOCKER_HOST=tcp://192.168.0.106:2375
    volumes:
      - ./data:/var/jenkins_home
    networks:
      - hugang

networks:
  hugang:
    external: true
