version: "3"

services:
  mysql-server:
    image: mysql:5.7
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1']
    networks:
      - hugang
networks:
  hugang:
    external: true

